node.master: true
node.data: true
bootstrap.memory_lock: true

cluster.name: elasticsearch-cluster
network.host: 0.0.0.0
discovery.type: single-node

xpack.security.enabled: false
xpack.license.self_generated.type: basic
xpack.monitoring.collection.enabled: false

#path.data: /usr/share/elasticsearch/data
#path.logs: /var/log/elasticsearch
path.repo: ["/esbackup"]
