node.master: true
node.data: true
#cluster.name: elastic-cluster
bootstrap.memory_lock: true
network.host: 0.0.0.0
xpack.security.enabled: false
xpack.license.self_generated.type: basic
xpack.monitoring.collection.enabled: false
