---
## Default Kibana configuration from kibana-docker.
## from https://github.com/elastic/kibana-docker/blob/master/build/kibana/config/kibana.yml
#
#server.name: kibana
#server.host: "0"

elasticsearch.url: http://${ELASTICSEARCH_URL}:9200

server.name: kibana
server.host: "0.0.0.0"
xpack.monitoring.ui.container.elasticsearch.enabled: false

logging.dest: stdout
#logging.dest: /opt/kalogs/kibana.log
